safe: true
lsi: false
author: Chris Keathley
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
rouge:
  line_numbers: true
line_numbers: true
description: This is where I think things.  Sometimes it's about code.  Sometimes that code works.
url: http://keathley.github.io
collections:
  talks:
    output: true
gems:
  - octopress-autoprefixer
  - jekyll-feed
